name: Build Package

on:
  repository_dispatch:
    types:
      - build

  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send Hooks BigLinux Build Package
        shell: bash
        run: |
          if [ -n "${{ github.event.client_payload.bigbranch }}" ];then
            branch=${{ github.event.client_payload.bigbranch }}
          else
            branch=${{ github.ref_name }}
          fi
          base="${{ github.event.client_payload.base }}"
          arch="${{ github.event.client_payload.arch }}"
          if [ -n "$(find -type f -name PKGBUILD)" ];then
            if [ "$base" = "manjaro" -a "$arch" = "x86_64" ];then
              packager=build-package
            elif [ "$base" = "manjaro" -a "$arch" = "arm" ];then
              packager=build-package-ARM
            elif [ "$base" = "archlinux" -a "$arch" = "x86_64" ];then
              packager=build-package-archlinux
            elif [ "$base" = "archlinux" -a "$arch" = "arm" ];then
              packager=build-package-archlinux-ARM
            else
              packager=build-package
            fi
            curl -X POST -H "Accept: application/json" -H "Authorization: token ${{ secrets.WEBHOOK_TOKEN }}" --data '{"event_type": "${{ github.repository }}", "client_payload": { "branch": "'$branch'", "url": "https://github.com/${{ github.repository }}"}}' https://api.github.com/repos/BigLinux-Package-Build/${packager}/dispatches
          fi
